# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Michele Di Maio
title: I turn data into stories by the day and I'm a podcaster by the night.
email: michele.dimaio@gmail.com
website: www.micheledimaio.com

# Social links
twitter_username: mikkysixx
github_username:  micheledm
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: micheledm
linkedin_username: micheleidmaio
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Michele and I'm a senior <mark>intelligence</mark> and <mark>insights</mark> manager. I have experience in CRM, product marketing and go-to-market. 
  
  I'm in love with technology and innovation and for the past 10 years I've been speaking about it <mark>in a podcast</mark> [called Digitalia](http://digitalia.fm).
  
  Also, I'm very serious about <mark>pizza</mark> and <mark>backpacking around Asia</mark>.

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some skills that I acquired during my working experience:
   - Excel ninja
   - Power Query & Power Pivot
   - Adobe Campaign
   - Oracle Datawarehouse
   - Sas
   - SQL
   
   And other things that I enjoy doing in my spare time:
   - Reading non-fiction and sci-fi
   - Coding (mostly Python)
   - Travelling
   - Cooking
   

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
